use_frameworks!

target 'DebugScreen_Example' do
  pod 'DebugScreen', :path => '../'
  pod 'SurfUtils/KeyboardPresentable', :git => 'https://github.com/surfstudio/iOS-Utils', :commit => '93c771258a88a5711f9d4851ec8a464035351616'
  pod 'Device.swift', :git => 'https://github.com/shelaranton/Device.swift', :commit => '5755e40c7de835938c6863abdc4553108e069e6f'

  target 'DebugScreen_Tests' do
    inherit! :search_paths
  end
end
