# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

pod_bundle_id = "org.cocoapods.DebugScreen"
pod_scheme = "DebugScreen"
pod_target = "DebugScreen"

example_bundle_id = "org.cocoapods.Pods-DebugScreen-Example"
example_scheme = "Pods-DebugScreen_Example"
example_target = "Pods-DebugScreen_Example"

derived_data_path = "./buildData"

default_platform :ios

platform :ios do

  ENV["FASTLANE_HIDE_CHANGELOG"] = "true"
  ENV["FASTLANE_SKIP_UPDATE_CHECK"] = "true"

  before_all do |lane, options|  
    # ensure_git_status_clean 
  end

  desc "Build Main scheme of Xcode target in Debug configuration"
  desc "Parameters:
  - clean: Pass **true** if you need to clean project before build
  "
  lane :build do |options|
    xcodebuild(
      scheme: pod_scheme,
      configuration: "Debug",
      clean: options[:clean],
      build: true,
      destination: "generic/platform=iOS\" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=\"",
      xcargs: "-sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build-for-testing",
      derivedDataPath: derived_data_path
    )
  end

  lane :example_build do |options|
    xcodebuild(
      scheme: example_scheme,
      configuration: "Debug",
      clean: options[:clean],
      build: true,
      destination: "generic/platform=iOS\" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=\"",
      xcargs: "-sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build-for-testing",
      derivedDataPath: derived_data_path
    )
  end

end